blueprint:
  name: Zigbee2MQTT - Sonoff SNZB01-P (GUI)
  description: "Blueprint Version: 04-11-2025\n
    Blueprint Name: Zigbee2MQTT - Sonoff SNZB01-P (MQTT Device Trigger) \n\n
    This blueprint uses MQTT `device` based triggers and it will be triggered only when the selected Device MQTT messages are received."
  domain: automation
  input:
    mode:
      name: Automation Modes
      description: https://www.home-assistant.io/docs/automation/modes/
      default: parallel
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    zigbee_device:
      name: Sonoff SBZN01-P Zigbee Switch
      description: Select the correct Sonoff Zigbee switch to use.
      selector:
        device:
          integration: mqtt
    # Button 1 Input Definition
    button_single:
      name: Single Press 
      description: Action to run on Button 1 - Single Press
      default: []
      selector:
        action: {}
    button_double:
      name: Double Press
      description: Action to run on Button 2 - Single Press
      default: []
      selector:
        action: {}
    button_long:
      name: Long Press
      description: Action to run on Button 2 - Double Press
      default: []
      selector:
        action: {}
mode: !input mode
max_exceeded: silent
trigger:
  # Button 1 Triggers
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: single
    id: button_single
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: double
    id: button_double
  - platform: device
    device_id: !input zigbee_device
    domain: mqtt
    type: action
    subtype: long
    id: button_long
condition: []
action:
  - choose:
      # Button 1 Actions
      - conditions:
          - condition: trigger
            id: button_single
        sequence: !input button_single
      - conditions:
          - condition: trigger
            id: button_double
        sequence: !input button_double
      - conditions:
          - condition: trigger
            id: button_long
        sequence: !input button_long
