blueprint:
  name: Sonoff Zigbee Switch (single, double, long)
  description: 'Control anything using Sonoff Zibee Switch SNZB-01P' 
  domain: automation
  input:
    switch:
      name: Switch
      description: Action sensor of Sonoff SNZB-01P Switch to use
      selector:
        entity:
          integration: mqtt

    press_single:
      name: Single button press
      description: Action to run on single button press
      default: []
      selector:
        action: {}
    
    press_double:
      name: Double button press
      description: Action to run on double button press
      default: []
      selector:
        action: {}
    
    press_long:
      name: Long button press
      description: Action to run on long button press
      default: []
      selector:
        action: {}


mode: queued
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input switch

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
      
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input press_single
      
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input press_double
      
      - conditions:
          - "{{ command == 'long' }}"
        sequence: !input press_long
      
